name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Display .NET version
        run: dotnet --version

      - name: Setup Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Display Python version
        run: python --version

      - name: Install pythonnet
        run: pip install pythonnet

      - name: Build .NET project
        run: dotnet build

      - name: Run Python script
        run: python pythonnet_minimal.py